apps/blog/urls.py
from django.conf.urls import url
from django.urls import path
from requests import delete

from apps.blog.views import (
    EditArticleView,
    list_drafts,
    list_articles,
    create_new_article,
    publish_new_article,
    article_detail,
    delete_article,
    delete_draft_article
)

app_name = "articles"
urlpatterns = [
    path("", view=list_articles, name="list"),
    path("new/", view=create_new_article, name="write_new"),
    path("publish/<uuid:article_uuid>/", view=publish_new_article, name="publish_article"),
    path("drafts/", view=list_drafts, name="drafts"),
    path("edit/<int:pk>/", EditArticleView.as_view(), name="edit_article"),
    path("delete/<int:pk>/", view=delete_article, name="delete_article"),
    path("delete_draft/<int:pk>/", view=delete_draft_article, name="delete_draft"),
    path("<uuid:article_uuid>/", view=article_detail, name="article"),
]

paywalled/urls.py
"""paywalled URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.apps import apps
from apps.authentication import views as auth_views
from apps.blog import views as blog_views
from apps.core import views as core_views
from django.contrib.sitemaps.views import sitemap
from django.views import defaults as default_views

urlpatterns = [
    path("", core_views.home, name="home"),
    path("", include("django.contrib.auth.urls")),
    path("login/success/", core_views.LoginRedirectView.as_view(), name="login_redirect"),
    path("signup/", auth_views.SignUpView.as_view(), name="signup"),
    path("signin/", RedirectView.as_view(pattern_name="login"), name="signin"),
    path("articles/", include("apps.blog.urls", namespace="articles")),
    path("payments/", include("apps.payments.urls", namespace="payments")),
    path('admin/', admin.site.urls),
    path("sitemap.xml", sitemap, name="sitemap"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("settings/", include("apps.accounts.urls", namespace="settings")),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns 

paywalled/templates/partials/article_list.html
{% load humanize %}
<div class="card mb-4" id="articles">
    <div class="card-body">
        <div class="list-group-item">
            <div class="list-group-item-figure">
                <a href="{% url 'articles:article' article.uuid %}" class="tile tile-lg tile-circle bg-warning">
                    <i class="bi bi-lightning-charge-fill"></i>
                </a>
            </div>
            <div class="list-group-item-body">
                <h3 style="font-size:1.3rem" class="list-group-item-title">
                    <a href="{% url 'articles:article' article.uuid %}">{{ article.title }}</a>
                </h3>
                <p class="list-group-item-subtitle mt-2">Updated
                    {{ article.date_published|naturaltime }}
                    . Total paid views: {{ article.get_view_count }}. Total reward:
                    {{ article.get_total_reward.total_reward }} sats</p>
            </div>
            {% if request.user == article.user %}
            <div class="list-group-item-figure">
                <a class="mr-1" href="{% url 'articles:edit_article' article.pk %}"><i class="bi bi-pencil"></i></a>
                <a class="ml-1" href="{% url 'articles:delete_article' article.pk %}"><i
                        class="bi bi-trash3-fill"></i></a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

paywalled/templates/partials/article_payment.html
<li class="timeline-item">
    <div class="timeline-figure">
        <span class="tile tile-circle tile-sm bg-warning"><i class="bi bi-lightning-charge-fill"></i></span>
    </div>
    <div class="timeline-body">
        <div class="media">
            <div class="media-body">
                <p class="mb-0">
                    {% if payment.user %}{{ payment.user.profile.get_screen_name }}{% else %}<i
                        class="bi bi-question-circle-fill"></i> {% endif %} paid
                    {{ payment.satoshi_amount }} sats to
                    {{ payment.purpose }} {% if mode == 'general' %}<a
                        href="{{ payment.article.get_absolute_url }}">"{{ payment.article.title }}"</a>{% endif %}
                </p><span class="timeline-date">{{ payment.created_at }}</span>
            </div>
        </div>
    </div>
</li>

paywalled/templates/partials/partial_invoice.html
{% load static %}

<style>
    .clickable {
        cursor: pointer !important;
    }
</style>

<form id="pub-lndInvoice">
    <fieldset>
        <div class="form-group">
            {% if purpose == 'publish' %}
            <label style="font-weight:600" for="lndInvoice">Pay $0.85 (2,100 sats) to publish</label>
            {% elif purpose == 'view' %}
            <label style="font-weight:600" for="lndInvoice">Pay $0.6 (1,500 sats) to view</label>
            {% endif %}
            <div class="input-group input-group-lg">
                <label class="input-group-prepend" for="lndInvoice">
                    <span class="badge"><i class="bi bi-lightning-charge-fill"></i></span>
                </label>
                <input type="text" class="form-control form-control-lg" id="pubLndInvoice"
                    value="{{ invoice.payment_request }}" readonly>
                <div class="input-group-append">
                    <span class="badge clickable" id="openWallet"><a href="lightning:{{ invoice.payment_request }}"><i
                                class="bi bi-wallet"></i> Open
                            wallet</a></span>
                    <span class="badge clickable" id="copyInvoice"><i class="bi bi-subtract"></i> Copy</span>
                    <span class="badge clickable" id="showQRCode"><i class="bi bi-qr-code-scan"></i> Show QR</span>
                </div>
            </div>
            <div class="mt-1" id="invoice-status" hx-get="/payments/check_payment/{{ invoice.pk }}/"
                hx-trigger="every 10s" hx-target="#invoice-status" hx-swap="innerhtml">Checking for payment<div
                    class="typing ml-1">
                    <span class="dot"></span> <span class="dot"></span> <span class="dot"></span>
                </div>
            </div>
        </div>
    </fieldset>
</form>
<!-- QR Code card -->
<div class="card text-black bg-warning" id="qrCodeCard">
    <div class="card-header"> Scan QR Code </div>
    <div class="card-body" id="qr-code"></div>
</div>
<!-- end QR Code card -->

{% block javascript %}
<script src="{% static 'js/copy.js' %}"></script>
<script src="{% static 'js/kjua.min.js' %}"></script>
<script>
    // copy lnd invoice to clipboard on click
    createCopy('{{ invoice.payment_request }}', 'copyInvoice', function () {
        alert('Lightning invoice was copied to clipboard');
    });

    // generate QR code with kjua
    $('#qr-code').kjua({
        text: 'lightning:{{ invoice.payment_request }}'
    });

    let qrCode = $("#qrCodeCard");
    // keep the code hidden until
    qrCode.hide()

    $("#showQRCode").on("click", function () {
        qrCode.toggle("fast")
    });
</script>
{% endblock %}

paywalled/templates/partials/partial_pub_invoice.html
{% load static %}

<style>
    .clickable {
        cursor: pointer !important;
    }
</style>

<form id="pub-lndInvoice">
    <fieldset>
        <div class="form-group">
            <label style="font-weight:600" for="lndInvoice">Pay $0.85 (2,100 sats) to publish</label>
            <div class="input-group input-group-lg">
                <label class="input-group-prepend" for="lndInvoice">
                    <span class="badge"><i class="bi bi-lightning-charge-fill"></i></span>
                </label>
                <input type="text" class="form-control form-control-lg" id="pubLndInvoice"
                    value="{{ payment.payment_request }}" readonly>
                <div class="input-group-append">
                    <span class="badge clickable" id="openWallet"><a href="lightning:{{ payment.payment_request }}"><i
                                class="bi bi-wallet"></i> Open
                            wallet</a></span>
                    <span class="badge clickable" id="copyInvoice"><i class="bi bi-subtract"></i> Copy</span>
                    <span class="badge clickable" id="showQRCode"><i class="bi bi-qr-code-scan"></i> Show QR</span>
                    <span class="badge clickable" id="checkPayment" hx-get="/payments/check_payment/{{ payment.pk }}/"
                        hx-trigger="click, every 10s" hx-target="#invoice-status" hx-swap="innerhtml"><i
                            class="bi bi-arrow-repeat"></i> Check
                        payment</span>
                </div>
            </div>
            <div id="invoice-status">Checking for payment...</div>
        </div>
    </fieldset>
</form>
<!-- QR Code card -->
<div class="card text-black bg-warning" id="qrCodeCard">
    <div class="card-header"> Scan QR Code </div>
    <div class="card-body" id="qr-code"></div>
</div>
<!-- end QR Code card -->

{% block javascript %}
<script src="{% static 'js/copy.js' %}"></script>
<script src="{% static 'js/kjua.min.js' %}"></script>
<script>
    // copy lnd invoice to clipboard on click
    createCopy('{{ payment.payment_request }}', 'copyInvoice', function () {
        alert('Lightning invoice was copied to clipboard');
    });

    // generate QR code with kjua
    $('#qr-code').kjua({
        text: 'lightning:{{ payment.payment_request }}'
    });

    let qrCode = $("#qrCodeCard");
    // keep the code hidden until
    qrCode.hide()

    $("#showQRCode").on("click", function () {
        qrCode.toggle("fast")
    });
</script>
{% endblock %}