apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.SettingsRedirectView.as_view(), name="settings"),
    path("profile/", views.UpdateProfileView.as_view(), name="profile"),
    path("emails/", views.UpdateEmailsView.as_view(), name="emails"),
]

apps/blog/urls.py
from django.conf.urls import url
from django.urls import path
from requests import delete

from apps.blog.views import (
    EditArticleView,
    list_drafts,
    list_articles,
    create_new_article,
    publish_new_article,
    article_detail,
    delete_article,
    delete_draft_article
)

app_name = "articles"
urlpatterns = [
    path("", view=list_articles, name="list"),
    path("new/", view=create_new_article, name="write_new"),
    path("publish/<uuid:article_uuid>/", view=publish_new_article, name="publish_article"),
    path("drafts/", view=list_drafts, name="drafts"),
    path("edit/<int:pk>/", EditArticleView.as_view(), name="edit_article"),
    path("delete/<int:pk>/", view=delete_article, name="delete_article"),
    path("delete_draft/<int:pk>/", view=delete_draft_article, name="delete_draft"),
    path("<uuid:article_uuid>/", view=article_detail, name="article"),
]

paywalled/urls.py
"""paywalled URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.apps import apps
from apps.authentication import views as auth_views
from apps.blog import views as blog_views
from apps.core import views as core_views
from django.contrib.sitemaps.views import sitemap
from django.views import defaults as default_views

urlpatterns = [
    path("", core_views.home, name="home"),
    path("", include("django.contrib.auth.urls")),
    path("login/success/", core_views.LoginRedirectView.as_view(), name="login_redirect"),
    path("signup/", auth_views.SignUpView.as_view(), name="signup"),
    path("signin/", RedirectView.as_view(pattern_name="login"), name="signin"),
    path("articles/", include("apps.blog.urls", namespace="articles")),
    path("payments/", include("apps.payments.urls", namespace="payments")),
    path('admin/', admin.site.urls),
    path("sitemap.xml", sitemap, name="sitemap"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("settings/", include("apps.accounts.urls", namespace="settings")),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns 

paywalled/templates/includes/footer.html
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-4 legal">
        <span>© 2021 Simple Complex</span>
      </div>
      <div class="col-xs-4" style="text-align: center;padding-top: 14px;">
        <small class="text-muted">
          <a href="https://github.com/vitorfs/parsifal/releases/latest" rel="noopener">v{{ parsifal_version }}</a>
        </small>
      </div>
      <div class="col-xs-4 social">
        <a href="https://github.com/vitorfs/parsifal" target="_blank" data-toggle="tooltip" title="Github" data-placement="top"><span class="fa fa-github"></span></a>
        <a href="https://twitter.com/parsif_al" target="_blank" data-toggle="tooltip" title="Twitter" data-placement="top"><span class="fa fa-twitter"></span></a>
        <a href="https://youtube.com/ParsifalReviews/" target="_blank" data-toggle="tooltip" title="Youtube" data-placement="top"><span class="fa fa-youtube"></span></a>
      </div>
    </div>
  </div>
</footer>

paywalled/templates/includes/header.html
{% load static %}
<header class="app-header app-header-light">
  <div class="top-bar container">
    <div class="top-bar-brand">
      <a href="/">Paywalled</a>
    </div>
    <div class="top-bar-list">
      <!-- .top-bar-item -->
      {% block header-far-right %}
      <div class="top-bar-item top-bar-item-right px-0 d-none d-sm-flex">
        <ul class="header-nav nav">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="btn btn-link" href="{% url 'articles:drafts' %}">My drafts</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-link" href="{% url 'articles:write_new' %}">Write new article</a>
          </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <div class="navbar-nav dropdown d-flex">
          <button class="btn-account w-100" type="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false"><span class="user-avatar user-avatar-md mr-lg-0"><img
                src="{% static 'images/user.png' %}" alt=""></span> <span
              class="account-summary pl-lg-2 d-none d-lg-block"><span
                class="account-name">{{ user.profile.get_screen_name }}</span></span>
          </button>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-arrow mr-3"></div>
            <h6 class="dropdown-header d-none d-lg-block d-lg-none"> {{ user.profile.get_screen_name }} </h6>
            <a class="dropdown-item" href=""><span class="dropdown-icon oi oi-person"></span>
              Profile</a>
            <a class="dropdown-item" href="{% url 'settings:settings' %}"><span
                class="dropdown-icon oi oi-pencil"></span> Edit Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><span class="dropdown-icon oi oi-account-logout"></span>
              Logout</a>
          </div><!-- /.dropdown-menu -->
        </div><!-- /.btn-account -->
        {% else %}
        <a class="btn-account btn btn-primary btn-lg" title="Sign up" href="{% url 'signup' %}">Sign up</a>
        <a class="btn-account btn-default btn-lg" title="Log in" href="{% url 'login' %}">Log in</a>
        {% endif %}
      </div><!-- /.top-bar-item -->
      {% endblock %}
    </div>
  </div>
</header>

paywalled/templates/includes/messages.html
{% if messages %} {% for message in messages %}
<div class="alert alert-{{ message.tags }} has-icon alert-dismissible fade show">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <div class="alert-icon">
    {% if message.tags == 'success' %}
    <span class="oi oi-check"></span>
    {% elif message.tags == 'warning' %}
    <span class="fa fa-bullhorn"></span>
    {% elif message.tags == 'error' %}
    <span class="oi oi-warning"></span>
    {% else %}
    <span class="oi oi-info"></span>
    {% endif %}
  </div>
  <p class="mb-0">{{ message }}</p>
</div>
{% endfor %} {% endif %}