apps/blog/urls.py
from django.conf.urls import url
from django.urls import path
from requests import delete

from apps.blog.views import (
    EditArticleView,
    list_drafts,
    list_articles,
    create_new_article,
    publish_new_article,
    article_detail,
    delete_article,
    delete_draft_article
)

app_name = "articles"
urlpatterns = [
    path("", view=list_articles, name="list"),
    path("new/", view=create_new_article, name="write_new"),
    path("publish/<uuid:article_uuid>/", view=publish_new_article, name="publish_article"),
    path("drafts/", view=list_drafts, name="drafts"),
    path("edit/<int:pk>/", EditArticleView.as_view(), name="edit_article"),
    path("delete/<int:pk>/", view=delete_article, name="delete_article"),
    path("delete_draft/<int:pk>/", view=delete_draft_article, name="delete_draft"),
    path("<uuid:article_uuid>/", view=article_detail, name="article"),
]

paywalled/urls.py
"""paywalled URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView, TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.apps import apps
from apps.authentication import views as auth_views
from apps.blog import views as blog_views
from apps.core import views as core_views
from django.contrib.sitemaps.views import sitemap
from django.views import defaults as default_views

urlpatterns = [
    path("", core_views.home, name="home"),
    path("", include("django.contrib.auth.urls")),
    path("login/success/", core_views.LoginRedirectView.as_view(), name="login_redirect"),
    path("signup/", auth_views.SignUpView.as_view(), name="signup"),
    path("signin/", RedirectView.as_view(pattern_name="login"), name="signin"),
    path("articles/", include("apps.blog.urls", namespace="articles")),
    path("payments/", include("apps.payments.urls", namespace="payments")),
    path('admin/', admin.site.urls),
    path("sitemap.xml", sitemap, name="sitemap"),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("settings/", include("apps.accounts.urls", namespace="settings")),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns 

apps/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from slugify import slugify
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
import uuid
from django.db.models import Sum

import codecs
from lnd_grpc import lnd_grpc

lnrpc = lnd_grpc.Client(
    lnd_dir = settings.LND_FOLDER,
    macaroon_path = settings.LND_MACAROON_FILE,
    tls_cert_path = settings.LND_TLS_CERT_FILE,
    network = settings.LND_NETWORK,
)

class ArticleQuerySet(models.query.QuerySet):
    """Personalized queryset created to improve model usability"""

    def get_published(self):
        """Returns only the published items in the current queryset."""
        return self.filter(status="P").order_by("-date_published")

    def get_drafts(self):
        """Returns only the items marked as DRAFT in the current queryset."""
        return self.filter(status="D").order_by("-date_published")


class Article(models.Model):
    DRAFT = "D"
    PUBLISHED = "P"
    STATUS = ((DRAFT, _("Draft")), (PUBLISHED, _("Published")))

    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="articles",
        on_delete=models.SET_NULL,
    )
    date_created = models.DateTimeField(auto_now_add=True)
    date_published = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255, null=True, unique=True)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    content = models.CharField(_("Content"), max_length=40000, blank=True)
    edited = models.BooleanField(default=False)
    objects = ArticleQuerySet.as_manager()

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ("-date_published",)

    def __str__(self):
        return self.title

    def get_absolute_url(self): 
        return reverse('articles:article', kwargs={ "article_uuid": self.uuid })

    def generate_pub_invoice(self):

        add_invoice_resp = lnrpc.add_invoice(value=settings.MIN_PUBLISH_AMOUNT, memo="Payment to Paywalled to publish article", expiry=settings.PUBLISH_INVOICE_EXPIRY)
        r_hash_base64 = codecs.encode(add_invoice_resp.r_hash, 'base64')
        r_hash = r_hash_base64.decode('utf-8')
        payment_request = add_invoice_resp.payment_request

        from apps.payments.models import Payment
        payment = Payment.objects.create(user=self.user, article=self, purpose=Payment.PUBLISH, satoshi_amount=settings.MIN_PUBLISH_AMOUNT, r_hash=r_hash, payment_request=payment_request, status='pending_payment')
        payment.save()

    def generate_view_invoice(self):

        add_invoice_resp = lnrpc.add_invoice(value=settings.MIN_VIEW_AMOUNT, memo=f"Payment to Paywalled to view article: {self.title}.", expiry=settings.VIEW_INVOICE_EXPIRY)
        r_hash_base64 = codecs.encode(add_invoice_resp.r_hash, 'base64')
        r_hash = r_hash_base64.decode('utf-8')
        payment_request = add_invoice_resp.payment_request

        from apps.payments.models import Payment
        payment = Payment.objects.create(article=self, purpose=Payment.VIEW, satoshi_amount=settings.MIN_VIEW_AMOUNT, r_hash=r_hash, payment_request=payment_request, status='pending_payment')
        payment.save()

    def get_view_count(self):
        return self.payments.filter(status="complete", purpose="view").count()

    def get_total_reward(self):
        return self.payments.filter(status="complete").aggregate(total_reward=Sum('satoshi_amount'))

apps/blog/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, ButtonHolder, Submit, HTML, Field, Button
from tinymce.widgets import TinyMCE
from apps.blog.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(
        widget=forms.HiddenInput(), required=False, initial=False
    )
    title = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-lg", "placeholder": "Article title"}),
        max_length=400,
        required=True,
        label="Title of your masterpiece",
    )
    content = forms.CharField(
        widget=TinyMCE(attrs={'cols': 80, 'rows': 30}),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            "title",
            "content",
            "status",
            "edited",
            HTML(
                """
                {% if payment_made %}
                <div id='paymentStatus' data-status='paid' class='alert alert-success' role='alert'>Payment confirmed. Thank you</div>
                {% else %}
                <div id="publishInvoice" class="mt-3">
                    {% if invoice %}
                    {% include 'partials/partial_invoice.html' with purpose='publish' %}
                    {% endif %}
                </div>
                {% endif %}
                """
            ),
            ButtonHolder(
                Submit("publish", "Publish article", css_class="publish btn btn-lg btn-success mr-2"),
                Submit("save", "Save as draft", css_class="draft btn btn-lg btn-subtle-primary mr-2"),
                HTML(
                    """
                    <a href="{% url 'articles:list' %}" class="btn btn-lg btn-subtle-dark">Cancel</a>
                    """
                )
                ),
        )

    class Meta:
        model = Article
        fields = ["title", "content", "status", "edited"]

apps/blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, ListView, UpdateView, DetailView, View
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _

from apps.authentication.helpers import AuthorRequiredMixin
from apps.blog.models import Article
from apps.blog.forms import ArticleForm

@login_required()
def list_drafts(request):
    drafts = request.user.articles.filter(status="D")
    context = {
        "drafts": drafts
    }
    return render(request, "blog/draft_list.html", context)

@login_required()
def list_articles(request):
    articles = request.user.articles.filter(status="P")
    context = {
        "articles": articles
    }
    return render(request, "blog/article_list.html", context)

@login_required()
def create_new_article(request):
    article = Article.objects.create(user=request.user)
    article.save()

    try:
        article.generate_pub_invoice()
    except:
        raise NotImplementedError()

    return redirect(reverse("articles:publish_article", kwargs={
        'article_uuid': article.uuid
    }))

@login_required()
def publish_new_article(request, article_uuid):

    article = request.user.articles.get(uuid=article_uuid)
    invoice = None
    payment_made = False

    try:
        # check existence of 'to publish' payments for this article and this user
        invoices = article.payments.filter(purpose='publish', user=request.user)
        if invoices:
            # we just need THE one
            invoice = invoices.first()
            if invoice.status == 'complete':
                payment_made = True
        else:
            # if no existing payment objects to view this article by this user
            article.generate_pub_invoice()
    except:
        raise NotImplementedError()

    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        # Publish article after payment
        if form.is_valid():
            article = form.save(commit=False)
            if "publish" in request.POST:
                article.status = Article.PUBLISHED
                messages.success(request, "Your article: '{}' has been published successfully".format(article.title))

            elif "save" in request.POST:
                article.status = Article.DRAFT
                messages.success(request, "Draft: '{}' has been saved successfully".format(article.title))
            article.save()

            return redirect(reverse("home"))

    else:
        form = ArticleForm(instance=article)
    
    return render(request, "blog/publish_article.html", {
        'article': article,
        'form': form,
        'invoice': invoice,
        'payment_made': payment_made
    })

@login_required()
def delete_draft_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect(reverse("articles:drafts"))

@login_required()
def delete_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect(reverse("home"))


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""

    model = Article
    message = _("Your article has been updated.")
    form_class = ArticleForm
    template_name = "blog/update_article.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse("home")

def article_detail(request, article_uuid):
    article = Article.objects.get(uuid=article_uuid)
    # assume the worst first, lol
    payment_made = False
    received_payments = None
    invoice = None

    try:
        # create session key if non-existent
        if not request.session.session_key:
            request.session.create()
        # check if logged in user has a "to view" invoice and whether paid?
        if request.user.is_authenticated:
            invoices = article.payments.filter(purpose='view', user=request.user)
            if invoices:
                # we just need THE one
                invoice = invoices.last()
                if invoice.status == 'complete':
                    payment_made = True
                    # add session key to invoice
                    invoice.session_key = request.session.session_key
            else:
                article.generate_view_invoice()
                invoice = article.payments.filter(purpose='view').latest("created_at")
        else:
            # get the most recent "to view" invoice for this particular session
            invoices = article.payments.filter(purpose='view', session_key=request.session.session_key)
            if invoices:
                # we just need THE one
                invoice = invoices.last()
                if invoice.status == 'complete':
                    payment_made = True
                    # add session key to invoice
                    invoice.session_key = request.session.session_key
            else:
                article.generate_view_invoice()
                invoice = article.payments.latest("modified_at")
    except:
        raise NotImplementedError()

    received_payments = article.payments.filter(status='complete').order_by('-modified_at')

    return render(request, "blog/article_detail.html", {
        'article': article,
        'invoice': invoice,
        'payment_made': payment_made,
        'received_payments': received_payments
    })

# @todo: on edit, check if lightning publish invoice has expired and create a new one. Also mark payment as expired

paywalled/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags humanize %}

{% block title %}{{ article.title|title }}{% endblock %}

{% block content %}

<style>
    .article-content {
        position: relative;
        overflow: hidden;
    }

    .article-content .continue-reading {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        text-align: center;
        margin: 0;
        padding: 30px 0;
        background-image: linear-gradient(to bottom, transparent, gray);
    }
</style>
<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <h1 class="mt-4">{{ article.title }}</h1>
            <p>Published {{ article.date_published|naturaltime }} by
                {{ article.user.profile.get_screen_name }}{% if article.user == request.user %}<a
                    class="btn btn-light ml-3" href="{% url 'articles:edit_article' article.id %}"
                    title="Edit this article"><i class="bi bi-pencil" aria-hidden="true"></i> Edit this
                    article</a>{% endif %}
            </p>
            <hr>
            <div class="article-content">
                {{ article.content|safe }}
                {% if not payment_made %}
                <div class="continue-reading">
                    <div class='alert alert-info mx-5' role='alert'>Pay the invoice below to keep reading</div>
                </div>
                {% endif %}
            </div>
            <hr>
            {% if payment_made %}
            <div id='paymentStatus' data-status='paid' class='alert alert-success' role='alert'>Payment confirmed. Thank
                you</div>
            {% else %}
            <div id="publishInvoice" class="mt-3">
                {% if invoice %}
                {% include 'partials/partial_invoice.html' with purpose="view" %}
                {% else %}
                <p>missing invoice</p>
                {% endif %}
            </div>
            {% endif %}
        </div>

        <div class="col-md-4">
            <div class="card text-light bg-dark">
                <div class="card-header"> Total reward: {{ article.get_total_reward.total_reward }} sats</div>
                <div class="card-body">
                    {% if received_payments %}
                    <ul class="timeline timeline-fluid">
                        {% for payment in received_payments %}
                        {% include 'partials/article_payment.html' %}
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No payments for this article at this time.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
    var $el, $outerdiv, $nextdiv, divs, totalHeight;

    totalHeight = 0
    $el = $('.continue-reading');
    $outerdiv = $el.parent();

    // set the max-height of the content div to 400px on load
    $outerdiv
        .css({
            "max-height": "400px"
        })

    // set a delay to allow the hx-trigger to run first
    var delay = 12000;
    setTimeout(function () {
        // check the data-status attribute on the alert div in the invoice-status area
        let paymentStatus = $('#paymentStatus').data("status");

        if (paymentStatus === "paid") {
            // if paid, remove the max-height css property
            $outerdiv
                .css({
                    "max-height": ""
                });

            // fade out continue reading
            $el.fadeOut();

            // prevent jump-down
            return false;
            console.log('Payment status', paymentStatus);
        }
    }, delay);
</script>
{% endblock javascript %}

paywalled/templates/blog/create_article.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

<form action="{% url 'articles:write_new' %}" enctype="multipart/form-data" id="article-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
        <button type="button" class="btn btn-lg btn-primary publish"
            hx-post="{% url 'payments:generate_pub_invoice' article.uuid %}" hx-target="#publishInvoice"
            hx-swap="beforeend">{% trans 'Publish Article' %}</button>
        <button type="button" class="btn btn-lg btn-default draft">{% trans 'Save as draft' %}</button>
        <a href="{% url 'articles:list' %}" class="btn btn-lg btn-default">{% trans 'Cancel' %}</a>

        <div id="publishInvoice">
            {% for payment in article.payments.all %}
            <p class="text-danger">{{ payment.payment_request }}</p>
            {% endfor %}
        </div>
    </div>
</form>
{{ form.media }}

{% endblock content %}

{% block modal %}
<script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}

paywalled/templates/blog/draft_list.html
{% extends 'base.html' %}
{% load static i18n %}
{% load humanize %}

{% block title %} {% trans 'Your Drafts' %} {% endblock %}

{% block head %}

{% endblock head %}

{% block content %}

<!-- Page Content -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mx-auto">
            <div class="list-group list-group-flush list-group-divider">
                {% for article in drafts %}
                <!-- Blog Post -->
                <div class="card mb-4" id="drafts">
                    <div class="card-body">
                        <div class="list-group-item">
                            <div class="list-group-item-figure">
                                <a href="{% url 'articles:article' article.uuid %}"
                                    class="tile tile-lg tile-circle bg-success">
                                    <i class="bi bi-lightning-charge-fill"></i>
                                </a>
                            </div>
                            <div class="list-group-item-body">
                                <h4 class="list-group-item-title">
                                    <a href="{% url 'articles:article' article.uuid %}">{{ article.title|title }}</a>
                                </h4>
                                <p class="list-group-item-text">{% trans 'Posted' %}
                                    {{ article.date_published|naturaltime }}
                                    by
                                    {{ article.user.profile.get_screen_name|title }} </p>
                            </div>
                            <div class="list-group-item-figure">
                                <a href="{% url 'articles:publish_article' article.uuid %}"
                                    class="btn btn-sm btn-primary">Edit & Publish</a>
                                <a class="btn btn-sm btn-light"
                                    href="{% url 'articles:delete_draft' article.pk %}">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p class="no-data">You have no drafts yet.</p>
                {% endfor %}
            </div>

            {% if is_paginated %}
            <ul class="pagination justify-content-center mb-4">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr;
                        {% trans 'Newer' %}</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span
                            class="sr-only">(current)</span></a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                        href="?page={{ page_obj.next_page_number }}">{% trans 'Older' %} &rarr;</a></li>
                {% else %}
                <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
                {% endif %}
            </ul>
            {% endif %}

        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->


{% endblock content %}

paywalled/templates/blog/publish_article.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

<form method="POST" action="" id="article-form">
    {% csrf_token %}
    {% crispy form %}
</form>

{% endblock content %}

{% block javascript %}
<script src="{% static 'js/articles.js' %}"></script>

<script>
    // publish button initially disabled
    $('.publish').prop('disabled', true);
    // set a delay to allow the hx-trigger to run first
    var delay = 12000;
    setTimeout(function () {
        // check the data-status attribute on the alert div in the invoice-status area
        let paymentStatus = $('#paymentStatus').data("status");

        if (paymentStatus === "paid") {
            // enable publish button
            $('.publish').removeAttr('disabled');
            console.log('Payment status', paymentStatus);
        }
    }, delay);
</script>
{% endblock javascript %}

paywalled/templates/blog/update_article.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

<form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data" id="article-form"
    method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
        <button type="button" class="btn btn-primary update">{% trans 'Update' %}</button>
        <button type="button" class="btn btn-default draft">{% trans 'Save as draft' %}</button>
        <a href="{% url 'articles:drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
</form>
{{ form.media }}

{% endblock content %}

{% block modal %}
<script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}